version: "3.8"

services:
  mongodb:
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /data/mongodb:/data/db
  redis:
    image: bitnami/redis:latest
    environment:
      REDIS_PASSWORD: redis_pass
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 100mb
    ports:
      - "6379:6379"
    restart: on-failure
